# Type stubs for llama_index.llms.ollama
from typing import Any, Dict, List, Optional, Generator, AsyncGenerator

class Ollama:
    def __init__(
        self,
        model: str = "llama2",
        base_url: str = "http://localhost:11434",
        request_timeout: float = 30.0,
        temperature: float = 0.75,
        context_window: int = 3900,
        additional_kwargs: Optional[Dict[str, Any]] = None,
        **kwargs: Any
    ) -> None: ...
    
    @property
    def metadata(self) -> Dict[str, Any]: ...
    
    def complete(self, prompt: str, formatted: bool = False, **kwargs: Any) -> Any: ...
    def stream_complete(self, prompt: str, formatted: bool = False, **kwargs: Any) -> Generator[Any, None, None]: ...
    async def acomplete(self, prompt: str, formatted: bool = False, **kwargs: Any) -> Any: ...
    async def astream_complete(self, prompt: str, formatted: bool = False, **kwargs: Any) -> AsyncGenerator[Any, None]: ...
    
    def chat(self, messages: List[Any], **kwargs: Any) -> Any: ...
    def stream_chat(self, messages: List[Any], **kwargs: Any) -> Generator[Any, None, None]: ...
    async def achat(self, messages: List[Any], **kwargs: Any) -> Any: ...
    async def astream_chat(self, messages: List[Any], **kwargs: Any) -> AsyncGenerator[Any, None]: ...